[default.limits]
forms = "64 kB"
json = "1 MiB"
msgpack = "2 MiB"
"file/jpg" = "5 MiB"

[default]
key = "a default app-key"
extra = false
ident = "Rocket"

[debug]
address = "0.0.0.0"
port = 9080
workers = 1
keep_alive = 0
log_level = "normal"

[release]
address = "127.0.0.1"
port = 8000
workers = 12
keep_alive = 5
log_level = "critical"
# don't use this key! generate your own and keep it private!
secret_key = "hPRYyVRiMyxpw5sBB1XeCMN1kFsDCqKvBi2QJxBVHQk="
key = "a release app-key"
extra = false

[global.tls]
certs = "./ca_cert.pem"
key = "./ca_key.pem"